<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CachingDemo.aspx.cs" Inherits="SampleWebFormApp.CachingDemo" %>
<%--<%@ OutputCache Duration="60" VaryByParam="City" %>--%>
<%@ Register Src="~/UserControls/TimeControl.ascx" TagName="timeCtrl" TagPrefix="custom" %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            The Current Time: 
            <h1>
                <asp:Label Text="text" runat="server" ID="lblTime" />
            </h1>
            <h2>
            Select the City:
                <asp:DropDownList runat="server" ID="cmbCity">
                    <asp:ListItem Text="New Delhi" />
                    <asp:ListItem Text="London" />
                    <asp:ListItem Text="New York" />
                    <asp:ListItem Text="Sydney" />
                    <asp:ListItem Text="San Francisco" />
                </asp:DropDownList>
                <asp:Button Text="Get Time" runat="server" ID="btnSubmit" OnClick="btnSubmit_Click"/>
            </h2>
        </div>
        <div>
            <h2>Only this section of the Page will be cached!!!</h2>
            <custom:timeCtrl runat="server" ID="myCtrol" />   
        </div>
        <div>
            <h2>Data Caching Example</h2>
            <asp:ListBox runat="server" ID="lstNames" Height="328px" Width="246px"></asp:ListBox>
        </div>
        <hr />
        <div>
            <h2>Caching in ASP.NET</h2>
            <div>
                <p>
                    Caching allows developers to store the Web content(Pages) in the memory for a certain period of time to deliver the pages in a faster manner when there is a huge network traffic. <br />
                    A Cache simply stores the output generated by a page in the memory and this saved output(cache) will serve the users in the future without a need to reconstruct the page. <br />
                    Caching can be any of the following: Page Caching, Data Caching and Fragment Caching. 
                </p>
                <p>
                    <b>
                        <u>Page Caching:</u>
                    </b> 
                    The whole Page is cached either in the server side or the client side, there will be duration attribute that tells the duration of the cache in the memory. In this case, the Page itself is cached. U can cache multiple versions of the Page using an attribute called VaryByParam. The value comes from the QueryString. 
                </p>
                <p><b><u>Fragment Caching:b><u>Fragment Caching:</u></b> Parts of the Pages are cached. It was a common feature before the concept of Ajax came into picture. Here we will create Custom User Controls and cache the output to the control and is used in the Web Page. Only the control part will be cached, the rest of the page will be rendered normally</p>
                <p><b><u>Data Caching:</u></b> 
                    In this case, instead of pages and parts of pages, the data that is supposed to be delivered will be cached. The data will be inmemory cache and will typically have expiry time to define the duration of its existance in the server.
                </p>
            </div>
        </div>
    </form>
</body>
</html>
