//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataComponentLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetailTable
    {
        public int EntryId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
