//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRecapApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleTable
    {
        public int SampleId { get; set; }
        public string SampleName { get; set; }
        public System.DateTime SampleDate { get; set; }
        public decimal SampleBill { get; set; }
    }
}
